modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/The-Acronym-Coders/Epos-Majorum/issues"

[[mods]]
    modId="eposmajorum"
    version="${file.jarVersion}"
    displayName="Epos Majorum"
    authors="SkySom, Lanse505, pupnewfster"
    description='''
        Adds Classes, Skills, and Leveling to Minecraft.

        Credits to:
            - Alexander for the Level-Up sound!
                - http://www.orangefreesounds.com/level-sound-effect/
    '''