modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/The-Acronym-Coders/epos/issues"

[[mods]]
    modId="epos"
    version="${version}"
    displayName="Epos"
    authors="SkySom, Lanse505, pupnewfster"
    description='''
Adds Classes, Skills, and Leveling to Minecraft.
'''

[[dependencies.epos]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    side="BOTH"
[[dependencies.epos]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
